name: CI

on:
  push:
    branches:
      - ops

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: ng test --browsers ChromeHeadless --watch=false
  publish:
    name: Build and Push Docker Image
    needs: build_job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo ${{ secrets.SOSTOOL_TOKEN }} | docker login ghcr.io -u eduardomirandaz --password-stdin
        
      - name: Build Docker image
        run: docker build -t ghcr.io/eduardomirandaz/sostool-frontend-cgmes:1.0.1 .

      - name: Push Docker image
        run: docker push ghcr.io/eduardomirandaz/sostool-frontend-cgmes:1.0.1
